### PR TITLE
Remove unnecessary apt packages, perform SHA256 check

### LINKED ISSUE #49: Add SHA checking
Instead of `curl ... | tar`, curl then verify the SHA256

Something like this... (from GoogleCloudPlatform/appengine-sidecars-docker#21)

```
GO_ARCHIVE="https://storage.googleapis.com/golang/go${GO_VERSION}.linux-amd64.tar.gz"
GO_ARCHIVE_SHA="${GO_ARCHIVE}.sha256"

curl -fsSL "$GO_ARCHIVE" -o go.tar.gz
curl -fsSL "$GO_ARCHIVE_SHA" -o go.tar.gz.sha256

echo "$(cat go.tar.gz.sha256)  go.tar.gz" | sha256sum -c -
```

### PR DESCRIPTION
**Pull request by broady**
Fixes #49.

### CODE REVIEW

**Comment by broady** [comment]
@dlorenc yes, I realized that just as you commented. PTAL.

**Comment by broady** [comment]
Saves approx. 150 MB in the image.

```
$ docker history gcr.io/google_appengine/golang
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
2ba04ea24635        48 seconds ago      /bin/sh -c #(nop) CMD ["go-wrapper" "run"]      0 B
01a0b0257647        48 seconds ago      /bin/sh -c #(nop) WORKDIR /go/src/app           0 B
c60825fda782        48 seconds ago      /bin/sh -c ln -s /go/src/app /app               11 B
573e9f99524a        49 seconds ago      /bin/sh -c curl https://raw.githubusercontent   2.481 kB
a681248f3ba7        50 seconds ago      /bin/sh -c mkdir -p /go/src/app /go/bin && ch   0 B
ec7be872e358        50 seconds ago      /bin/sh -c #(nop) ENV GOPATH=/go:/go/src/app/   0 B
fcbb6d746f16        51 seconds ago      /bin/sh -c #(nop) ENV PATH=/go/bin:/usr/local   0 B
1d23d04566a8        53 seconds ago      /bin/sh -c curl -sSL https://storage.googleap   318.1 MB
aed2b04b115d        29 minutes ago      /bin/sh -c #(nop) ENV GO_WRAPPER_COMMIT=3cdd8   0 B
5fe5a6452f0f        29 minutes ago      /bin/sh -c #(nop) ENV GO_VERSION=1.6.3          0 B
32b2f869713f        29 minutes ago      /bin/sh -c apt-get update     && apt-get inst   7.847 MB
5d735d16c1df        3 weeks ago         /bin/sh -c apt-get -q update &&     apt-get i   7.911 MB
193fa0359d01        3 weeks ago         /bin/sh -c #(nop) ENV PORT=8080                 0 B
e8eb529bd074        3 weeks ago         /bin/sh -c #(nop) ENV DEBIAN_FRONTEND=noninte   0 B
abf0692dab5b        3 weeks ago         /bin/sh -c #(nop) CMD []                        0 B
b21b3e3bc691        8 weeks ago         /bin/sh -c #(nop) ADD file:8086d9d18e7f7c09e5   123.6 MB
b29ae6f49e5a        8 weeks ago         /bin/sh -c #(nop) ARG DEBIAN_SUITE              0 B
3bc7cdb36864        12 months ago       /bin/sh -c #(nop) ENV PATH=/usr/local/sbin:/u   0 B
4bfc20f0ed66        12 months ago       /bin/sh -c #(nop) ENV DEBIAN_FRONTEND=noninte   0 B
```

**Comment by broady** [comment]
Update #51.

**Comment by broady** [comment]
This broke cgo (no more gcc), do we care? I don't think so.

**Comment by okdave** [comment]
I don't think we care, but we should wait to see if many people were using it and we didn't realise.

**Comment by broady** [comment]
How can we tell who's using cgo? Do you think we should break the image the next time we update?

**Comment by okdave** [comment]
I mean, happy to push this out – but we might need to reevaluate if we hear that it's caused a lot of pain.

**Comment by dlorenc** [comment]
I'd lean toward not pushing it out on a Friday :)

**Comment by broady** [comment]
Yeah definitely no intention to push this stuff any time soon 😁

**Pull request merged**
