### PR TITLE
add license tests to structure tests

### PR DESCRIPTION
**Pull request by sharifelgamal**
License tests are automated tests to check that all packages installed in the image conform to Google's open source licensing stardards. Check out https://github.com/GoogleCloudPlatform/runtimes-common/tree/master/structure_tests#license-tests for more details.

### CODE REVIEW

**Comment by sharifelgamal** [comment]
@broady

**Comment by broady** [comment]
LGTM - @zombiezen @shantuo @adams-sarah

**Comment by zombiezen** [comment]
:+1:

**Comment by shantuo** [comment]
LGTM

**Pull request merged**
