### PR TITLE
Add Go 1.16 and update base Ubuntu image to 18.04

### PR DESCRIPTION
**Pull request by gorshunovr**
This PR adds Go 1.16 image, updates Ubuntu to 18.04, and updates default travis build to latest Go version.
Please, review. Thank you.

### CODE REVIEW

**Comment by gorshunovr** [comment]
Hello @donmccasland! Could you review PR, please? Thank you!

**Comment by cagataygurturk** [comment]
Any idea when this can be merged?

**Comment by KyleJu** [comment]
Hi Cloud team, any update on when this PR can be landed? @donmccasland Thanks!

**Comment by jahjahbin** [comment]
We had a massive delay/silence on this, and I apologize for that. We recently launched some of the newest versions of Go for App Engine Flex. Check out [this page](https://cloud.google.com/appengine/docs/flexible/lifecycle/support-schedule) to find which versions of Go we support, but please note the "end of support" dates.

The newest versions are supported via [Google Cloud's buildpacks](https://github.com/GoogleCloudPlatform/buildpacks).

**Pull request closed without merging**
