### PR TITLE
Update to Go 1.6.2

### PR DESCRIPTION
**Pull request by mkaesz**

### CODE REVIEW

**Comment by mkaesz** [comment]
I signed it!

**Comment by okdave** [comment]
@bro

**Comment by okdave** [comment]
Thanks for the PR – sorry for the delay in responding.

There seems to be a couple of issues though with the current change: the wrapper commit you link to doesn't seem to exist and there's no /1.6.2/ path in the docker-library/golang repo.

@broady

**Comment by broady** [comment]
This brings up an interesting point - we should add tests for this repo.

This is the source for the current 1.6 image. Let's use that?
https://github.com/docker-library/golang/blob/master/1.6/Dockerfile

```
ENV GOLANG_VERSION 1.6.2
ENV GOLANG_DOWNLOAD_URL https://golang.org/dl/go$GOLANG_VERSION.linux-amd64.tar.gz
ENV GOLANG_DOWNLOAD_SHA256 e40c36ae71756198478624ed1bb4ce17597b3c19d243f3f0899bb5740d56212a
```

**Comment by broady** [comment]
Superseded by #46

**Pull request closed without merging**
