### PR TITLE
Update to Go 1.6.3

### PR DESCRIPTION
**Pull request by broady**

### CODE REVIEW

**Comment by broady** [comment]
@raggi how does this get built/released? Manually, right?

**Comment by raggi** [comment]
Dave now owns this. We've had customer confusion when this doesn't launch with the update to Standard, so it's likely you should wait for the Standard ship.

**Comment by okdave** [comment]
Probably best to coordinate with @adamtanner, he's looking at 1.6.3 for standard. But, IMO, I don't think we need to worry too much about minor releases (after all, standard is already on 1.6.2 and flex has been left at 1.6).

Otherwise, LGTM.

**Comment by adamtanner** [comment]
LGTM. Go 1.6.3 should ship with 1.9.43.

**Comment by broady** [comment]
@raggi @adamtanner I forget how these are built. I remember @gmlewis needed to press a button to get these shipped.

**Pull request merged**
